baseline:
  branch: main

standards:
  format: []
  lint:
    - "python3 -m ruff check ."
  typecheck: []
  test_fast:
    - "python3 -m pytest -q tests/tasks tests/market_data tests/finance_data tests/earnings_data tests/price_target_data"
  test_full:
    - "python3 -m pytest -q"
  format_fix:
    - "python3 -m ruff format ."
  lint_fix:
    - "python3 -m ruff check --fix ."

architecture:
  layers:
    - name: "api"
      path_glob: "api/**"
      forbid_imports_from:
        - "ui/**"
    - name: "tasks"
      path_glob: "tasks/**"
      allow_imports_from:
        - "core/**"
        - "tasks/**"
        - "monitoring/**"
  blessed_patterns:
    - "Idempotent storage reconciliation flows"
    - "Environment-driven runtime configuration"

dependencies:
  denylist:
    - "left-pad"
  allowlist: []
  lockfile_required: true

api:
  public_globs:
    - "api/endpoints/**"
    - "api/service/settings.py"
    - "api/service/app.py"
    - "core/runtime_config.py"
  breaking_change_policy: "strict"

thresholds:
  drift_score_fail: 35
  category_weights:
    security: 40
    api: 35
    architecture: 25
    behavioral: 25
    dependency: 20
    test: 25
    performance: 15
    style: 5
    docs: 3
    config_infra: 15

auto_remediate:
  enabled: false
  max_files_changed: 50
  safe_directories:
    - "api/**"
    - "core/**"
    - "tasks/**"
    - "tests/**"
    - "docs/**"
    - ".github/workflows/**"
  commands:
    - "python3 -m ruff format ."
    - "python3 -m ruff check --fix ."

risk_controls:
  protected_globs:
    - "deploy/sql/postgres/migrations/**"
    - "infra/**"
    - ".github/workflows/deploy.yml"
    - "api/endpoints/system.py"
  require_tests_passing_before_automerge: true

reporting:
  markdown_path: "artifacts/drift_report.md"
  json_path: "artifacts/drift_report.json"
  patch_path: "artifacts/drift_remediation.patch"

detection:
  lookback_days: 7
  exclude_globs:
    - "artifacts/**"
