
\"\"\"
Schema definitions for the Asset Allocation project.
Defines the columns for Market Data, Finance Data, Earnings Data, and Price Target Data.
\"\"\"

MARKET_DATA_COLUMNS = [
    "open", "high", "low", "close", "volume", "symbol", "return_1d", "return_5d",
    "return_20d", "return_60d", "vol_20d", "vol_60d", "rolling_max_252d", "drawdown",
    "true_range", "atr_14d", "sma_20d", "sma_50d", "sma_200d", "sma_20_gt_sma_50",
    "sma_50_gt_sma_200", "sma_20_crosses_above_sma_50", "sma_20_crosses_below_sma_50",
    "sma_50_crosses_above_sma_200", "sma_50_crosses_below_sma_200", "bb_width_20d",
    "range_close", "volume_z_20d", "volume_pct_rank_252d",
    "gap_atr", "trend_50_200", "above_sma_50", "range_20", "compression_score"
]

FINANCE_DATA_COLUMNS = [
    "symbol", "total_revenue", "operating_revenue", "cost_of_revenue", "gross_profit",
    "operating_expense", "selling_general_and_administration",
    "general_and_administrative_expense", "salaries_and_wages", "other_gand_a",
    "selling_and_marketing_expense", "research_and_development",
    "depreciation_amortization_depletion_income_statement",
    "depreciation_and_amortization_in_income_statement", "other_operating_expenses",
    "operating_income", "net_non_operating_interest_income_expense",
    "interest_income_non_operating", "interest_expense_non_operating",
    "other_income_expense", "gain_on_sale_of_security", "earnings_from_equity_interest",
    "special_income_charges", "restructuring_and_mergern_acquisition", "write_off",
    "other_non_operating_income_expenses", "pretax_income", "tax_provision",
    "net_income_common_stockholders", "net_income",
    "net_income_including_noncontrolling_interests",
    "net_income_continuous_operations", "net_income_extraordinary",
    "preferred_stock_dividends", "diluted_ni_availto_com_stockholders", "basic_eps",
    "diluted_eps", "basic_average_shares", "diluted_average_shares",
    "total_operating_income_as_reported", "total_expenses",
    "net_income_from_continuing_and_discontinued_operation", "normalized_income",
    "interest_income", "interest_expense", "net_interest_income", "ebit", "ebitda",
    "reconciled_cost_of_revenue", "reconciled_depreciation",
    "net_income_from_continuing_operation_net_minority_interest",
    "total_unusual_items_excluding_goodwill", "total_unusual_items", "normalized_ebitda",
    "tax_rate_for_calcs", "tax_effect_of_unusual_items", "total_assets",
    "current_assets", "cash_cash_equivalents_and_short_term_investments",
    "cash_and_cash_equivalents", "cash_financial", "cash_equivalents",
    "other_short_term_investments", "receivables", "accounts_receivable",
    "gross_accounts_receivable", "allowance_for_doubtful_accounts_receivable",
    "inventory", "raw_materials", "work_in_process", "finished_goods",
    "current_deferred_assets", "current_deferred_taxes_assets", "hedging_assets_current",
    "other_current_assets", "total_non_current_assets", "net_ppe", "gross_ppe",
    "properties", "land_and_improvements", "buildings_and_improvements",
    "machinery_furniture_equipment", "other_properties", "leases",
    "accumulated_depreciation", "goodwill_and_other_intangible_assets", "goodwill",
    "other_intangible_assets", "investments_and_advances", "long_term_equity_investment",
    "investmentin_financial_assets",
    "financial_assets_designatedas_fair_value_through_profitor_loss_total",
    "available_for_sale_securities", "financial_assets", "non_current_deferred_assets",
    "non_current_deferred_taxes_assets", "other_non_current_assets",
    "total_liabilities_net_minority_interest", "current_liabilities",
    "payables_and_accrued_expenses", "payables", "accounts_payable", "total_tax_payable",
    "income_tax_payable", "other_payable", "current_accrued_expenses",
    "pensionand_other_post_retirement_benefit_plans_current",
    "current_debt_and_capital_lease_obligation", "current_debt", "commercial_paper",
    "other_current_borrowings", "current_deferred_liabilities",
    "current_deferred_taxes_liabilities", "current_deferred_revenue",
    "other_current_liabilities", "total_non_current_liabilities_net_minority_interest",
    "long_term_debt_and_capital_lease_obligation", "long_term_debt",
    "long_term_capital_lease_obligation", "non_current_deferred_liabilities",
    "non_current_deferred_taxes_liabilities", "non_current_deferred_revenue",
    "tradeand_other_payables_non_current", "other_non_current_liabilities",
    "total_equity_gross_minority_interest", "stockholders_equity", "capital_stock",
    "preferred_stock", "common_stock", "additional_paid_in_capital", "retained_earnings",
    "gains_losses_not_affecting_retained_earnings",
    "foreign_currency_translation_adjustments", "other_equity_adjustments",
    "other_equity_interest", "minority_interest", "total_capitalization",
    "preferred_stock_equity", "common_stock_equity", "capital_lease_obligations",
    "net_tangible_assets", "working_capital", "invested_capital", "tangible_book_value",
    "total_debt", "net_debt", "share_issued", "ordinary_shares_number",
    "operating_cash_flow", "cash_flow_from_continuing_operating_activities",
    "net_income_from_continuing_operations", "operating_gains_losses",
    "gain_loss_on_investment_securities", "depreciation_amortization_depletion",
    "depreciation_and_amortization", "depreciation", "deferred_tax",
    "deferred_income_tax", "asset_impairment_charge",
    "unrealized_gain_loss_on_investment_securities", "stock_based_compensation",
    "excess_tax_benefit_from_stock_based_compensation", "other_non_cash_items",
    "change_in_working_capital", "change_in_receivables",
    "changes_in_account_receivables", "change_in_inventory",
    "change_in_payables_and_accrued_expense", "change_in_payable",
    "change_in_tax_payable", "change_in_income_tax_payable",
    "change_in_account_payable", "change_in_other_current_assets",
    "change_in_other_current_liabilities", "change_in_other_working_capital",
    "investing_cash_flow", "cash_flow_from_continuing_investing_activities",
    "net_ppe_purchase_and_sale", "purchase_of_ppe", "sale_of_ppe",
    "net_business_purchase_and_sale", "purchase_of_business",
    "net_investment_purchase_and_sale", "purchase_of_investment", "sale_of_investment",
    "net_other_investing_changes", "financing_cash_flow",
    "cash_flow_from_continuing_financing_activities", "net_issuance_payments_of_debt",
    "net_long_term_debt_issuance", "long_term_debt_issuance", "long_term_debt_payments",
    "net_short_term_debt_issuance", "short_term_debt_issuance",
    "short_term_debt_payments", "net_common_stock_issuance", "common_stock_issuance",
    "common_stock_payments", "cash_dividends_paid", "common_stock_dividend_paid",
    "net_other_financing_charges", "end_cash_position", "changes_in_cash",
    "effect_of_exchange_rate_changes", "beginning_cash_position",
    "other_cash_adjustment_outside_changein_cash", "capital_expenditure",
    "issuance_of_capital_stock", "issuance_of_debt", "repayment_of_debt",
    "repurchase_of_capital_stock", "free_cash_flow", "market_cap", "enterprise_value",
    "pe_ratio", "forward_pe_ratio", "peg_ratio", "ps_ratio", "pb_ratio",
    "enterprises_value_revenue_ratio", "enterprises_value_ebitda_ratio", "rev_qoq",
    "rev_yoy", "net_inc_yoy", "fcf_yoy", "gross_margin", "op_margin", "fcf_margin",
    "debt_to_assets", "current_ratio", "net_income_ttm", "operating_cash_flow_ttm",
    "roa_ttm", "long_term_debt_to_assets", "gross_margin_ttm", "asset_turnover_ttm",
    "shares_outstanding", "piotroski_roa_pos", "piotroski_cfo_pos",
    "piotroski_delta_roa_pos", "piotroski_accruals_pos", "piotroski_leverage_decrease",
    "piotroski_liquidity_increase", "piotroski_no_new_shares",
    "piotroski_gross_margin_increase", "piotroski_asset_turnover_increase",
    "piotroski_f_score", "ev_ebitda", "peg_proxy",
    "rev_growth_slope_6q", "fcf_slope_6q", "ebitda_margin", "margin_delta_qoq",
    "net_debt", "shares_change_yoy", "fpe", "ev_rev"
]

EARNINGS_DATA_COLUMNS = [
    "symbol", "reported_eps", "eps_estimate", "surprise", "date_parsed",
    "surprise_pct", "surprise_mean_4q", "surprise_std_8q", "beat_rate_8q"
]

PRICE_TARGET_DATA_COLUMNS = [
    "ticker", "tp_mean_est", "tp_std_dev_est", "tp_high_est", "tp_low_est",
    "tp_cnt_est", "tp_cnt_est_rev_up", "tp_cnt_est_rev_down", "disp_abs",
    "disp_norm", "disp_std_norm", "rev_net", "rev_ratio", "rev_intensity",
    "disp_norm_change_30d", "tp_mean_change_30d", "tp_mean_slope_90d",
    "disp_z"
]

ALL_DATA_SCHEMAS = {
    "market_data": MARKET_DATA_COLUMNS,
    "finance_data": FINANCE_DATA_COLUMNS,
    "earnings_data": EARNINGS_DATA_COLUMNS,
    "price_target_data": PRICE_TARGET_DATA_COLUMNS
}
